### ISSUE TITLE
Actual issue that might affect user experience 

### ISSUE THREAD

**Issue by Bejofo** [Bobopodia/fluffy-rotary-phone#3]
Audio is no longer auto playing. I also get a warning about unsafe scripts and 
Suspected cause is either the favicon and the audio being loading from another domain.
Suggested fix is to host the favicon and audio on the repository.

**Comment by Bejofo** [comment]
Also related favicon is also no longer autoloading.

**Comment by Bejofo** [comment]
Favicon is loaded from http://www.golocalprov.com/cache/images/remote/http_s3.amazonaws.com/images.golocalworcester.com/soviet-union.gif
Notice how it is loaded over 'http' not 'https'. The 's' in 'https' stands for **_SECURE_**. The browser by default is blocking it.

**Comment by Bobopodia** [comment]
its fine.
